name: pvpmc-usa-2026-dnv-apis
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - pip
  - ipykernel>=7.2.0
  - matplotlib>=3.10.9
  - pandas>=3.0.2
  - pvlib>=0.15.1
  - pip:
    - dnv-solarfarmer>=0.2.0
    - solcast>=1.3.1
